import Head from 'next/head'
import { Layout } from '@/layouts/Layout';
import { ControlDeviceTable } from '@/components/ControlDevice/ControlDeviceTable';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ControlDeviceTable />
      </div>
    </Layout>
  )
}
